# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]


jobs:
 
  build-lin:

    runs-on: ubuntu-latest

    steps:
  
      - name: Run a one-line script
        run: sh ./train.sh

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          ls -a
          pwd
          
      - name: for my purpose 
        run: sh ./train.sh
        
      - name: waiting num 5
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          ls -a
          whoami
          env
          
  build-win:
    runs-on: windows-latest

    steps:

      - name: Run a one-line script
        run: ls
